steps:
  -
    name: "Lint"
    command: .ci/scripts/lint
    agents:
      swift: "2.2"
  -
    name: "Mac"
    command: .ci/scripts/test-osx
    agents:
      swift: "2.2"
  -
    name: "iOS"
    command: .ci/scripts/test-ios
    agents:
      swift: "2.2"    
    env:
      FL_SLATHER_BUILDKITE_ENABLED: true
      FL_SLATHER_COVERALLS_ENABLED: true

