lane :lint do
	swiftLint(
		mode: :lint, 
		config_file: '.swiftlint.yml'
	)
end

desc "Runs the feature kit tests"
lane :test_featurekit do

	carthage(platform: "Mac")

	scan(
		project: "FeatureKit.xcodeproj",
		scheme: "FeatureKit",
		destination: "platform=OS X"
	)

end

desc "Runs the feature kit tests"
lane :test_featurekitui do

	carthage(platform: "iOS")

	scan(
		project: "FeatureKit.xcodeproj",
		scheme: "FeatureKitUI",
		destination: "platform=iOS Simulator,name=iPhone 6s"
	)

end
