
lane :lint do

    swiftLint(
        mode: :lint, 
        config_file: '.swiftlint.yml'
    )
end

platform :ios do

  before_all do
	carthage(platform: "iOS")
  end

  desc "Runs all the tests"
  lane :test do

    scan(
      project: "Features.xcodeproj",
      scheme: "iOS Features",
      output_directory: ".ci/xcodebuild-data",
      xcargs: "-derivedDataPath .ci/xcodebuild-data"
    )

  end

end

platform :mac do

  before_all do
	carthage(platform: 'Mac')
  end

  desc "Runs all the tests"
  lane :test do

    scan(
      project: "Features.xcodeproj",
      scheme: "macOS Features",
      output_directory: ".ci/xcodebuild-data",
      xcargs: "-derivedDataPath .ci/xcodebuild-data"
    )

  end
  
end
